version: '3'

services:
  fitrep:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3001:3000"
    volumes:
      - .:/usr/src/fitrep
    env_file:
      - environments/dev
    links:
      - redis

  database:
    image: postgres
    env_file:
      - environments/dev
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

volumes:
  db_data:
  redis:
